### ISSUE TITLE
Add a second robot

### ISSUE THREAD

**Issue by stevensacks** [RaijnAU/toy-robot#6]
Create a second robot with a different color.

Be able to move each robot around the board using the WASD and Arrow Keys.

WASD = First Robot
Arrows = Second Robot

**Comment by stevensacks** [comment]
Robots should not be able to occupy the same space. If a robot attempts to walk into a space where another robot is present, do not allow it. Same as if it was the edge of the table.

**Comment by RaijnAU** [comment]
Latest push ready for review.
